# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 8453
  start_block: 0
  contracts:
  - name: CreditSystem
    address:
    - 0x7b8Ec48F7fb9d637589b9864386A470690D49c4b
    handler: src/EventHandlers.ts
    events:
    - event: CreditsDeposited(address indexed user, address indexed token, uint256 tokenAmount, uint256 creditsMinted, uint256 usdRate, uint256 timestamp)
    - event: CreditsDepositedETH(address indexed user, uint256 ethAmount, uint256 creditsMinted, uint256 ethUsdRate, uint256 timestamp)
    - event: CreditsUsed(address indexed user, uint256 amount, uint256 useType, uint256 entityId, uint256 timestamp)
unordered_multichain_mode: true
preload_handlers: true
